export const GET_COUNTRY='GET_COUNTRY';
export const FINISH_COUNTRY='FINISH_COUNTRY';
export const GET_SUMMARY='GET_SUMMMARY';
export const FINISH_SUMMARY='FINISH_SUMMARY';
export const RESET_COUNTRY='RESET_COUNTRY';